[relaychain]
default_command = "polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9955

[[relaychain.nodes]]
name = "charlie"
validator = true
ws_port = 9966

[[parachains]]
id = 5128
chain_spec_path = "../_chainspec/zeta-devnet-plain.json"

[[parachains.collators]]
name = "dave"
ws_port = 9988
command = "polkadot-omni-node"

[[parachains.collators]]
name = "eve"
ws_port = 9999
command = "polkadot-omni-node"
