[relaychain]
default_command = "polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9955

[[parachains]]
id = 5123
chain_spec_path = "../_chainspec/zeta_devnet_plain.json"

[parachains.collator]
name = "charlie"
ws_port = 9988
command = "polkadot-omni-node"
