exclude = [
    "**/*nested-1000.toml",
    "**/invalid/*",
    "**/node_modules/**",
    "target",
    "target/**",
    "test-data/**",
]
include = ["**/*.toml"]

[formatting]
align_comments = false
align_entries = false
allowed_blank_lines = 1
array_auto_collapse = true
array_auto_expand = true
compact_arrays = true
compact_entries = false
compact_inline_tables = false
indent_string = "    "
indent_tables = false
inline_table_expand = true
reorder_arrays = true
reorder_inline_tables = false
reorder_keys = false
trailing_newline = true

# don't re-order order-dependent rustflags
[[rule]]
include = [".cargo/config.toml"]
keys = ["build"]

[rule.formatting]
reorder_arrays = false

[[rule]]
include = ["Cargo.toml"]
keys = ["workspace.dependencies"]

[rule.formatting]
reorder_keys = true

[[rule]]
include = ["**/Cargo.toml"]
keys = ["build-dependencies", "dependencies", "dev-dependencies"]

[rule.formatting]
reorder_keys = true
